name: Publish Python Package
on:
    release:
        types: [created]
jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-python@v2
        - name: Install dependencies
          run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install setuptools wheel twine
        - name: Build and publish
          env:
            TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
            TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
          run: |
            python3 setup.py sdist bdist_wheel
            twine upload --verbose --repository-url https://test.pypi.org/legacy/ -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }} dist/*